version: '3'
services:
  mongodb:
    image: mongo
    volumes:
      - mongo_data:/data/db
  express:
    build: .
    depends_on:
      - mongodb
    volumes:
      - ./:/app
    ports:
      - "8081:8080"
    stdin_open: false
    tty: true

volumes:
  mongo_data:
