version: '3'
services:
  mongodb:
    image: mongo
    volumes:
      - mongo_data:/data/db
  couchdb:
    image: couchdb
    ports:
      - "5984:5984"
  express:
    build: .
    depends_on:
      - mongodb
      - couchdb
    volumes:
      - ./:/app
    ports:
      - "8081:8080"
    stdin_open: false
    tty: true

volumes:
  mongo_data:
